### PR TITLE
removed tooltip hovers when on IOS

### PR DESCRIPTION
**Pull request by human37**
It detects the browser and if on IOS is removes the tooltip hovers. Everything else works the same.

### CODE REVIEW

**Comment by human37** [comment]
Also this is kinda hacky, if there is a better way let me know

**Review by evad1n — COMMENTED** [review]
wtf no. don't just remove them. Imma make a branch and push. you test it on safari and tell me if it works. I'd rather try to fix them then remove them completely.

**Comment by evad1n** [comment]
you said it only happens for the leaderboard right?

**Comment by human37** [comment]
It happens with the leaderboard modal and the about modal (anything that opens a card). I just think the hover tooltips should be removed from all mobile instances as they don't make sense with tapping. I can check if your change works though. In order to test on mobile you have to close and reopen them a couple times in a row and it sticks.

**Pull request merged**
