### PR TITLE
Going serverless with Netlfiy Functions and FaunaDB

### LINKED ISSUE #13: Use aws/netlify lambda functions and ditch the heroku server completely
I think this can be done, especially since you are using an AWS database now. It will speed up our requests and make it serverless.

### PR DESCRIPTION
**Pull request by evad1n**
Not optimized for possibly hitting limits of free tier for functions, so that can be done in the future.

Also only tested locally using netlify dev, so make sure to check out the pull request preview that Netlfiy will deploy.

I added main as branch deploy so this pull request will hopefully preview, might have to fiddle with it.

I added a bunch of stuff in the DEV-README.md file, and removed a lot of the TODOs that were already completed.

### CODE REVIEW

**Comment by evad1n** [comment]
Also this is just a test (essentially a stage test), and before production we need to remove all those debug console logs and stuff

**Review by human37 — APPROVED** [review]
Looking clean like Mr. clean

**Review by mabraham23 — APPROVED** [review]
Really really good guyz. glad I could contribute

**Comment by human37** [comment]
Good work Mark

**Pull request merged**
